### ISSUE TITLE
ubuntu下python3.6.1，安装正常，打开127.0.0.1，左侧目录树点不开，报下面的错误，是哪里出的问题？

### ISSUE THREAD

**Issue by wwwdelphi** [EasyMicroPython/EMP-IDE-OFFLINE#4]
Welcome to 1ZLAB-EMPIDE!
Password: 
WebREPL connected
>>> ide.device_info()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'ide' isn't defined
>>> ide.memory_status()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'ide' isn't defined
>>> ide.tree()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'ide' isn't defined

**Comment by Singein** [comment]
esp32上是否安装了 emp-1zlab?

**Comment by wwwdelphi** [comment]
安装了，用http://www.1zlab.com/ide/#/是正常的，可以写代码和上传

**Comment by wwwdelphi** [comment]
刚刚看到终端上还有这个，是不是个错误？
127.0.0.1 - - [04/Feb/2020 17:25:17] "GET /editor.worker.bundle.js HTTP/1.1" 404 -
127.0.0.1 - - [04/Feb/2020 17:25:18] "GET /static/fonts/MaterialIcons-Regular.570eb838.woff2 HTTP/1.1" 304 -
127.0.0.1 - - [04/Feb/2020 17:25:42] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [04/Feb/2020 17:25:43] "GET /editor.worker.bundle.js HTTP/1.1" 404

**Comment by Singein** [comment]
> 安装了，用http://www.1zlab.com/ide/#/是正常的，可以写代码和上传

emp-ide-offline是先前构建的版本, 暂时还不支持最新的结合了串口的版本

> 刚刚看到终端上还有这个，是不是个错误？
127.0.0.1 - - [04/Feb/2020 17:25:17] "GET /editor.worker.bundle.js HTTP/1.1" 404 -
127.0.0.1 - - [04/Feb/2020 17:25:18] "GET /static/fonts/MaterialIcons-Regular.570eb838.woff2 HTTP/1.1" 304 -
127.0.0.1 - - [04/Feb/2020 17:25:42] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [04/Feb/2020 17:25:43] "GET /editor.worker.bundle.js HTTP/1.1" 404

这个理论上来说是个错误,  没有获取到对应的js资源.
`editor.worker.bundle.js ` 是 monoca editor(即网页上面的编辑器组件)的依赖,

**Comment by wwwdelphi** [comment]
> > 安装了，用[http://www.1zlab.com/ide/#/是正常的，可以写代码和上传](http://www.1zlab.com/ide/#/%E6%98%AF%E6%AD%A3%E5%B8%B8%E7%9A%84%EF%BC%8C%E5%8F%AF%E4%BB%A5%E5%86%99%E4%BB%A3%E7%A0%81%E5%92%8C%E4%B8%8A%E4%BC%A0)
> 
> emp-ide-offline是先前构建的版本, 暂时还不支持最新的结合了串口的版本
> 
> > 刚刚看到终端上还有这个，是不是个错误？
> > 127.0.0.1 - - [04/Feb/2020 17:25:17] "GET /editor.worker.bundle.js HTTP/1.1" 404 -
> > 127.0.0.1 - - [04/Feb/2020 17:25:18] "GET /static/fonts/MaterialIcons-Regular.570eb838.woff2 HTTP/1.1" 304 -
> > 127.0.0.1 - - [04/Feb/2020 17:25:42] "GET / HTTP/1.1" 200 -
> > 127.0.0.1 - - [04/Feb/2020 17:25:43] "GET /editor.worker.bundle.js HTTP/1.1" 404
> 
> 这个理论上来说是个错误, 没有获取到对应的js资源.
> `editor.worker.bundle.js ` 是 monoca editor(即网页上面的编辑器组件)的依赖,

**Comment by Singein** [comment]
![图片](https://user-images.githubusercontent.com/18239246/73899835-c5f44300-48c8-11ea-8f11-27f1f2b98d24.png)
抱歉, 时间久了 我也记不太清了, 这个版本也更新了, 当前版本是基于emp-ext构建的.
由于之前一直是我一个人开发, 所以git的工作流我一直没有太规范 , 所有的东西都在主分支下进行.

**Comment by Singein** [comment]
如果有兴趣或者需要, 可以加我微信, `love_you_actually`, 我工作空余时间 可以一起讨论.
其实我现在很想把整个项目推倒重来, 但是一直没什么精力和动力...

**Comment by wwwdelphi** [comment]
十分感谢，我对这个非常感兴趣，现在加您微信

**Comment by l20031018** [comment]
> Welcome to 1ZLAB-EMPIDE!
> Password:
> WebREPL connected
> 
> > > > ide.device_info()
> > > > Traceback (most recent call last):
> > > > File "", line 1, in 
> > > > NameError: name 'ide' isn't defined
> > > > ide.memory_status()
> > > > Traceback (most recent call last):
> > > > File "", line 1, in 
> > > > NameError: name 'ide' isn't defined
> > > > ide.tree()
> > > > Traceback (most recent call last):
> > > > File "", line 1, in 
> > > > NameError: name 'ide' isn't defined

in boot.py find from emp_ide import *  ,  change to import emp_ide as ide
